on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run-test
        id: run-test
        run: |
          sudo apt install -y curl
          docker run -d -p 8080:80 nginx:stable-alpine3.19-slim
          curl -v http://127.0.0.1:8080
        
