on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run-test
        id: run-test
        run: |
          sudo apt install -y curl
          docker run -d -p 80:80 --name httpserver nginx:stable-alpine3.19-slim
          ip_server=`docker inspect httpserver | jq -r .[].NetworkSettings.IPAddress`
          echo "IP: $ip_server"
          echo ""
          echo "####################"
          echo ""
          docker ps
          docker inspect httpserver          
          echo ""
          echo "####################"
          echo ""
          curl -v http://127.0.0.1:80
        
